[csd] actually fix CSD for 6.2
This reverts 26a8536 and fixes the actual issue with the CSD: a missing
comma, as indicated by the logs of the failed testKuduCSDExistence.

2019-05-30 01:56:22,818 DEBUG main:com.cloudera.csd.CsdBundle: Could not read service descriptor for csd [KUDU6_2-6.x.0]
com.fasterxml.jackson.databind.JsonMappingException: Unexpected character ('"' (code 34)): was expecting comma to separate Object entries
 at [Source: (byte[])"// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by ap"[truncated 20770 bytes]; line: 25, column: 15] (through reference chain: com.fasterxml.jackson.module.mrbean.generated.com.cloudera.csd.descriptors.ServiceDescriptor["compatibility"]->com.fasterxml.jackson.module.mrbean.generated.com.cloudera.csd.descriptors.CompatibilityDescriptor["cdhVersion"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:394)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:353)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1711)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:290)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3091)
	at com.cloudera.csd.components.JsonSdlObjectMapper.readValue(JsonSdlObjectMapper.java:106)
	at com.cloudera.csd.components.JsonSdlParser.parse(JsonSdlParser.java:71)
	at com.cloudera.csd.components.JsonSdlParser.parse(JsonSdlParser.java:60)
	at com.cloudera.csd.CsdBundle.parseAndValidateSdl(CsdBundle.java:151)
	at com.cloudera.csd.CsdBundle.<init>(CsdBundle.java:78)
	at com.cloudera.csd.components.CsdLocalRepository.getRepositoryInfo(CsdLocalRepository.java:226)
	at com.cloudera.csd.components.CsdLocalRepository$$EnhancerByMockitoWithCGLIB$$438b6f7.CGLIB$getRepositoryInfo$9(<genera
...[truncated 18574802 bytes]...
e [KUDU]

Change-Id: Iffc2a84d78e9f0d8622237bcc8e277802c849da0